{{- if not .Values.secrets.existingSecret }}
{{- $full := include "sentinelops.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinelops.secretName" . }}
  labels:
    {{- include "sentinelops.labels" (dict "root" . "component" "secrets") | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRES_DSN: {{ printf "postgresql://sentinel:%s@%s-postgres:5432/sentinel" .Values.secrets.postgresPassword $full | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.secrets.rabbitmqPassword | quote }}
  AMQP_URL: {{ printf "amqp://sentinel:%s@%s-rabbitmq:5672/" .Values.secrets.rabbitmqPassword $full | quote }}
  API_KEYS: {{ .Values.secrets.apiKeys | quote }}
  INGEST_API_KEY: {{ index (splitList "," .Values.secrets.apiKeys) 0 | trim | quote }}
  WEBHOOK_URL: {{ .Values.secrets.webhookUrl | quote }}
{{- end }}
